### ISSUE TITLE
How to get user id after login?

### ISSUE THREAD

**Issue by wst24365888** [up9cloud/flutter_libtdjson#2]
Hi, I just read your example code and I'm wondering that what I should do to get the user id after successfully logged in (after checkAuthenticationCode)? I want to get the user info through the user id. Actually, I can see some logs about the user info in the debug console, but I don't know how to get it. Any answer will be appreciated, thanks!

Btw, nice package!

**Comment by up9cloud** [comment]
你可以在 example/lib/service/telegram_service.dart 這隻裡面的 _afterReceive 攔截你想要的資訊？
