### ISSUE TITLE
android build error

### ISSUE THREAD

**Issue by zk320520** [up9cloud/flutter_libtdjson#3]
> Could not resolve io.github.up9cloud:td:1.7.0.
     Required by:
         project :app > project :libtdjson
      > Could not resolve io.github.up9cloud:td:1.7.0.
         > Could not get resource 'https://maven.pkg.github.com/up9cloud/android-libtdjson/io/github/up9cloud/td/1.7.0/td-1.7.0.pom'.
            > Could not GET 'https://maven.pkg.github.com/up9cloud/android-libtdjson/io/github/up9cloud/td/1.7.0/td-1.7.0.pom'. Received status code 400 from server: Bad Request

**Comment by up9cloud** [comment]
the file exist, see https://github.com/up9cloud/android-libtdjson/packages/876227
You have to follow the instruction, see the part for android in readme.md
