### ISSUE TITLE
receive and authorizationStateClosed

### ISSUE THREAD

**Issue by dwap** [up9cloud/flutter_libtdjson#4]
https://github.com/up9cloud/flutter_libtdjson/blob/05c71c5a95916e21a53effed94bd3fc49327ef5a/lib/service.dart#L157
change, better here:
https://github.com/up9cloud/flutter_libtdjson/blob/05c71c5a95916e21a53effed94bd3fc49327ef5a/lib/service.dart#L117
json.decode and send map
and check authorizationStateClosed

Example:
```
String? s = _rawClient.td_json_client_receive(clientId, timeout);
      if (s != null) {
        Map<String, dynamic> j = json.decode(s);
        sendPortToMain.send(j);
        if (j['@type'] == 'updateAuthorizationState') {
          if (j['authorization_state']['@type'] == 'authorizationStateClosed') {
            break;
          }
        }
      }
```

**Comment by up9cloud** [comment]
Well, the main reason that I didn't check state in isolation is about performance.
Isolation communicate with main is actually doing the serialization, I tried not to do decode things inside.
(And I think it's rarely people would close the service... If you're in dev mode, you may set the timeout to something like 2s to save your time)

**Comment by dwap** [comment]
"And I think it's rarely people would close the service..." - this is debatable, tdlib has memory leak issues. Example: https://github.com/tdlib/td/issues/1676 and others...
I rewrote my microservice (python) to dart based on your package (isolate everything with its re-creation). The result pleased me. thx!

**Comment by up9cloud** [comment]
@dwap I tried to send custom event to solve this. Now, it will close the receiving loop as soon as posible.
