### ISSUE TITLE
Save authentication state in SharedPreferences to avoid constantly logging in

### ISSUE THREAD

**Issue by sbordeyne** [up9cloud/flutter_libtdjson#6]
Hello,

Nice dart implementation of TDLib, it's a pain to use without it. I have a question though, where is the authentication key stored when performing the auth flow for telegram using this library ?

I want to store the auth token locally so that I can use https://core.telegram.org/method/auth.importAuthorization to not have to do the auth login flow every time I open my app after closing it.

If that is handled automatically (i.e. the tdlib service saves its state locally and the user is never logged out unless an `@type: logOut` request is sent), is there a way to simply detect whether the user is currently logged in ?

Thanks,

**Comment by up9cloud** [comment]
You don't have to export auth token and store it locally, tdlib will handle it. just call the receive loop function, listen and handle the updateAuthorizationState event. see https://github.com/up9cloud/flutter_libtdjson/blob/62456bd2af4679b400fc2d3964578e0f00777684/lib/service.dart#L255 and https://github.com/up9cloud/flutter_libtdjson/blob/62456bd2af4679b400fc2d3964578e0f00777684/example/lib/service/telegram_service.dart#L95
